# Generated by Django 5.2.1 on 2025-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
