# Generated by Django 5.2.1 on 2025-05-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_watch_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='watch',
        ),
    ]
